### ISSUE TITLE
Inheritable front matter

### ISSUE THREAD

**Issue by BFergerson** [voqal/voqal#133]
chrome.md uses this to select browser:
```yaml
selector:
  integration:
    chrome:
      connected: true
  computer:
    activeApplication:
      processName:
        # Windows
        - brave.exe
        - chrome.exe
        # MacOs
        - Brave Browser
        - Google Chrome
        # Linux
        - brave
        - chrome
```

youtube/tools/next_video.yaml uses this to select browser:
```yaml
selector:
  computer:
    activeApplication:
      processName:
        # Windows
        - brave.exe
        - chrome.exe
        # MacOs
        - Brave Browser
        - Google Chrome
        # Linux
        - brave
        - chrome
```

---

To avoid dupe config, front matter config should be inheritable
